### PR TITLE
Add support for Swagger model definitions.

### PR DESCRIPTION
**Pull request by fotinakis**
https://github.com/wordnik/swagger-core/wiki/Datatypes#wiki-complex-types

Following the same pattern as `swagger_api`, you simply do:

``` ruby
      swagger_model :Tag do
        description "A Tag object."
        property :id, :integer, :required, "User Id"
        property :name, :string, :optional, "Name", foo: "test"
      end
```

And then the root JSON object will have:

```
"models": {
  "id": "Tag",
  "required": ["id"],
  "description": "A Tag object.",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name",
      "foo": "test",
    },
    "id": {
      "type": "integer",
      "description": "User Id",
    }
  }
}
```

### CODE REVIEW

**Comment by peyterkim** [comment]
@fotinakis - is the `swagger_model` definition supposed to be an example of a response? 

to make it show up in the sidebar of UI, I had to reference it as `type :Tag` in `swagger_api`, although it doesn't display the information correctly.

My swagger action and model are defined like so: 

```
  swagger_model :User do
    description 'A User object'
    property :id, :integer, :required, "User ID"
    property :firstname, :string, :required, "First name"
    property :lastname, :string, :required, "Last name"
  end

  swagger_api :index do
    summary 'Returns list of users'
    response :unauthorized
    response :not_acceptable
    response :unprocessable_entity
    type :User
  end
```

but the output looks like this: 

screen shot 2016-04-22 at 12 54 22 pm

If it's supposed to be just an example of a response, is there any way we can put dummy data rather than  it having display a 0 for an integer and "string" for a string. Also, in the schema, the attributes are all "optional", but what does this imply? For a response, all the attributes being returned aren't really "optional", correct?

**Comment by fotinakis** [comment]
@peyterkim I have no idea anymore on this project, I'm the author of a different gem now ([swagger-blocks](https://github.com/fotinakis/swagger-blocks)) which has correct support for what you're looking for. Sorry!

**Comment by peyterkim** [comment]
@fotinakis - oh! i was trying to get swagger-blocks to work before trying this. with swagger ui 2.0, it now looks for swagger.json rather than api-docs.json. In order to generate swagger.json, do you have to run 

```
swagger_data = Swagger::Blocks.build_root_json(SWAGGERED_CLASSES)
File.open('swagger.json', 'w') { |file| file.write(swagger_data.to_json) }
```
every time?

I had the route go to `/apidocs`, which goes to Apidocs#index:
```
  def index
    render json: Swagger::Blocks.build_root_json(SWAGGERED_CLASSES)
  end
```

this just generated a JSON blob. Shouldn't this work right out of the box for Rails? How did you set up Swagger UI to get swagger-blocks to work?

**Comment by fotinakis** [comment]
Yes, it works out of the box, you don't have to write files at all. Swagger UI can be configured to point at any JSON endpoint not just swagger.json. See: https://github.com/swagger-api/swagger-ui#swaggerui

-- If you have further questions, let's move this discussion to the swagger-blocks repo, since these questions are not about swagger-docs.

**Pull request merged**
